### ISSUE TITLE
Issue with Angular Universal - SSR not AoT compatible

### ISSUE THREAD

**Issue by dexbytesmanish** [biig-io/ngx-smart-modal#160]
Below line is stopping to run Angular Universal SSR :
https://github.com/biig-io/ngx-smart-modal/blob/118bf6ed37d9235bb33ad565627101b7085c1b93/src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts#L94

**Comment by maximelafarie** [comment]
Maybe we should add event listeners with Angular `Renderer2` as explained [here](https://malcoded.com/posts/server-rendering-pitfalls).

**Comment by khylias** [comment]
Hi @dexbytesmanish , @maximelafarie,

recently we have implement an Angular with SSR and we didn't have any problem with ngx-smart-modal component.
However, with another npm packages, we have a trouble with window and document javascript object then we have create window and document mocks.

**Comment by dexbytesmanish** [comment]
I am getting below error while running SSR server :
ReferenceError: window is not defined
    at NgxSmartModalComponent.module.exports.NgxSmartModalComponent.ngOnDestroy

How can I get rid of this ?

**Comment by ima-tech** [comment]
I have the exact same issue. Any idea how to prevent that?

**Comment by khylias** [comment]
Hi @dexbytesmanish @ima-tech,

For fix your error, we build a mock of window element as below, in your `server.ts`:

```
const domino = require('domino');
const win = domino.createWindow('<body></body>');

global['window'] = win;
```

Don't forget to install domino !

**Comment by dexbytesmanish** [comment]
> Hi @dexbytesmanish @ima-tech,
> 
> To fix your error, you have to build a mock of `window` element as shown below, in your `server.ts` file:
> 
> ```
> const domino = require('domino');
> const win = domino.createWindow('<body></body>');
> 
> global['window'] = win;
> ```
> Don't forget to install domino !
> With this method, you can mock all of DOM component, for example:
> 
> ```
> global['document'] = win.document;
> global['navigator'] = win.navigator;
> ```

Still the same error :

ERROR { Error: Uncaught (in promise): Error: This method is not implemented in DominoAdapter: getCookie
Error: This method is not implemented in DominoAdapter: getCookie
    at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
    at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
    at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
    at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
    at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
    at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
    at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
    at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
    at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
    at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117362:31)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117319:17)
    at /var/www/html/project-angular6/dist/server.js:117421:17
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116969:31)
    at Object.onInvokeTask (/var/www/html/project-angular6/dist/server.js:4204:33)
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116968:36)
    at Zone.module.exports.Zone.runTask (/var/www/html/project-angular6/dist/server.js:116736:47)
    at drainMicroTaskQueue (/var/www/html/project-angular6/dist/server.js:117143:35)
    at module.exports.ZoneTask.invokeTask (/var/www/html/project-angular6/dist/server.js:117048:21)
    at Server.ZoneTask.invoke (/var/www/html/project-angular6/dist/server.js:117033:48)
  rejection:
   Error: This method is not implemented in DominoAdapter: getCookie
       at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
       at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
       at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
       at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
       at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
       at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
       at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
       at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
       at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
       at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      Error: This method is not implemented in DominoAdapter: getCookie
          at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
          at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
          at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
          at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
          at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
          at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
          at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
          at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
          at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
          at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Zone],
        _name: 'angular',
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value:
         Error: This method is not implemented in DominoAdapter: getCookie
             at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
             at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
             at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
             at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
             at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
             at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
             at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
             at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
             at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
             at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
(node:7532) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR { Error: Uncaught (in promise): Error: This method is not implemented in DominoAdapter: getCookie
Error: This method is not implemented in DominoAdapter: getCookie
    at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
    at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
    at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
    at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
    at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
    at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
    at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
    at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
    at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
    at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117362:31)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117319:17)
    at /var/www/html/project-angular6/dist/server.js:117421:17
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116969:31)
    at Object.onInvokeTask (/var/www/html/project-angular6/dist/server.js:4204:33)
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116968:36)
    at Zone.module.exports.Zone.runTask (/var/www/html/project-angular6/dist/server.js:116736:47)
    at drainMicroTaskQueue (/var/www/html/project-angular6/dist/server.js:117143:35)
    at module.exports.ZoneTask.invokeTask (/var/www/html/project-angular6/dist/server.js:117048:21)
    at Server.ZoneTask.invoke (/var/www/html/project-angular6/dist/server.js:117033:48)
  rejection:
   Error: This method is not implemented in DominoAdapter: getCookie
       at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
       at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
       at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
       at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
       at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
       at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
       at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
       at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
       at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
       at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      Error: This method is not implemented in DominoAdapter: getCookie
          at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
          at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
          at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
          at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
          at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
          at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
          at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
          at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
          at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
          at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Zone],
        _name: 'angular',
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value:
         Error: This method is not implemented in DominoAdapter: getCookie
             at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
             at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
             at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
             at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
             at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
             at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
             at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
             at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
             at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
             at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
ERROR { Error: Uncaught (in promise): Error: This method is not implemented in DominoAdapter: getCookie
Error: This method is not implemented in DominoAdapter: getCookie
    at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
    at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
    at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
    at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
    at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
    at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
    at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
    at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
    at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
    at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117362:31)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117319:17)
    at /var/www/html/project-angular6/dist/server.js:117421:17
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116969:31)
    at Object.onInvokeTask (/var/www/html/project-angular6/dist/server.js:4204:33)
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116968:36)
    at Zone.module.exports.Zone.runTask (/var/www/html/project-angular6/dist/server.js:116736:47)
    at drainMicroTaskQueue (/var/www/html/project-angular6/dist/server.js:117143:35)
    at module.exports.ZoneTask.invokeTask (/var/www/html/project-angular6/dist/server.js:117048:21)
    at Server.ZoneTask.invoke (/var/www/html/project-angular6/dist/server.js:117033:48)
  rejection:
   Error: This method is not implemented in DominoAdapter: getCookie
       at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
       at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
       at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
       at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
       at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
       at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
       at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
       at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
       at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
       at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      Error: This method is not implemented in DominoAdapter: getCookie
          at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
          at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
          at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
          at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
          at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
          at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
          at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
          at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
          at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
          at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Zone],
        _name: 'angular',
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value:
         Error: This method is not implemented in DominoAdapter: getCookie
             at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
             at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
             at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
             at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
             at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
             at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
             at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
             at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
             at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
             at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }

**Comment by khylias** [comment]
This error refers to DominoAdapter's getCookie method, please check Domino's problems.

I didn't give you a plug&play solution, adapt it to your project.
